### ISSUE TITLE
字符左右边距需要调整

### ISSUE THREAD

**Issue by subframe7536** [Photonico/Photonico_Code#1]
r和j看起来偏右
![image](https://user-images.githubusercontent.com/78338239/201375706-53b95e36-bcb8-4fa2-b0e4-46d38ec0919b.png)
![image](https://user-images.githubusercontent.com/78338239/201375746-1dcb644c-9cef-40d9-89b3-b315e45e5e5a.png)

**Comment by Photonico** [comment]
感谢提供建议，第一次做字体没什么经验，下版本我修正这个问题。

**Comment by subframe7536** [comment]
~~间距可以对着 fira code 或者 jetbrains mono 抄~~

**Comment by Photonico** [comment]
> ~间距可以对着 fira code 或者 jetbrains mono 抄~
已经更新到了试用版中: https://github.com/Photonico/Photonico_Code/blob/main/Releases/Photonico%20Current.ttf
p.s.
我一直是参考 Fira Code 和 Courier Prime 的，不过文件基础是 Fira Code 而这个字体是 Slab-serif , 改动还是非常大的(基本是保留框架，2000多个字符重新设计)，很多字符结构不得不大改。
`j`这个字符是真的难设计，它整体重心都是右偏的（而`i`是左偏的，两个放一起就显得离得远），FiraCode 字体对他的处理手段是让上面的点向左篇一点点，我参考了一下，不知道会如何。

**Comment by subframe7536** [comment]
j可以把横和勾拉长+点偏左。i的点其实也是偏左的
不过目前就ide而言，对我来说已经可以用了，加油❤️

**Comment by Photonico** [comment]
> j可以把横和勾拉长+点偏左。i的点其实也是偏左的 不过目前就ide而言，对我来说已经可以用了，加油heart

我在 Current 里面都按你说的微调了一些，感谢建议。

P.S. 我去年也有一个"艺术作品"(我本职应该是做科学计算，却沉迷做这些 hhh)：涵盖亮色和暗色的VSCode主题包：https://github.com/Photonico/Photonica
感兴趣可以品尝一下～
