### ISSUE TITLE
Any plans for cyrillic glyphs?

### ISSUE THREAD

**Issue by capiet** [Photonico/Photonico_Code#3]

**Comment by Photonico** [comment]
Hi,

thanks for the message.
Cyrillic glyphs are a huge project for me. 
And I don't have any experience of using that.
So, I am seeking collaborators on Cyrillic glyphs.

Cheers,

**Comment by capiet** [comment]
> Hi,
> 
> 
> 
> thanks for the message.
> 
> Cyrillic glyphs are a huge project for me. 
> 
> And I don't have any experience of using that.
> 
> So, I am seeking collaborators on Cyrillic glyphs.
> 
> 
> 
> Cheers,
> 
> 
> 
> 

Hello. Thank you for the reply, so I close the issue.
